# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXwHf5bzTSLoP-z9UPKFor2nTTE1ecVM
"""

# ==============================
# DATA SCIENCE ASSIGNMENT
# Clustering and Fitting
# ==============================

# Upload file
from google.colab import files
uploaded = files.upload()

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.linear_model import LinearRegression
from scipy.stats import skew, kurtosis

# ==============================
# Load dataset
# ==============================
data = pd.read_csv(list(uploaded.keys())[0])

print("First 5 rows:")
print(data.head())

print("\nColumn names:")
print(data.columns)

# ==============================
# Data Cleaning
# ==============================

# Convert column names to lowercase
data.columns = data.columns.str.lower()

print("\nColumns after lowercase:", data.columns)

# Automatically detect columns
gdp_col = [col for col in data.columns if 'gdp' in col][0]
life_col = [col for col in data.columns if 'life' in col][0]
pop_col = [col for col in data.columns if 'pop' in col][0]

# Select and rename
data = data[[gdp_col, life_col, pop_col]]
data.columns = ['gdp_per_capita', 'life_expectancy', 'population']

# Drop missing values
data = data.dropna()

print("\nShape after cleaning:", data.shape)

# Safe sampling (prevents crash)
data = data.sample(min(200, len(data)))

print("\nCleaned Data:")
print(data.head())

# ==============================
# Statistical Moments
# ==============================
print("\nStatistical Moments:")

print("\nMean:")
print(data.mean())

print("\nVariance:")
print(data.var())

print("\nSkewness:")
print(data.apply(skew))

print("\nKurtosis:")
print(data.apply(kurtosis))

# ==============================
# Relational Plot (Scatter)
# ==============================
plt.figure()
plt.scatter(data['gdp_per_capita'], data['life_expectancy'])
plt.xlabel("GDP per Capita")
plt.ylabel("Life Expectancy")
plt.title("GDP vs Life Expectancy")
plt.show()

# ==============================
# Categorical Plot (Histogram)
# ==============================
plt.figure()
plt.hist(data['gdp_per_capita'], bins=20)
plt.title("Distribution of GDP per Capita")
plt.xlabel("GDP per Capita")
plt.ylabel("Frequency")
plt.show()

# ==============================
# Statistical Plot (Heatmap)
# ==============================
plt.figure()
sns.heatmap(data.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

# ==============================
# Clustering (K-Means)
# ==============================
kmeans = KMeans(n_clusters=3, random_state=0)
data['Cluster'] = kmeans.fit_predict(data[['gdp_per_capita', 'life_expectancy']])

plt.figure()
plt.scatter(data['gdp_per_capita'], data['life_expectancy'], c=data['Cluster'])
plt.xlabel("GDP per Capita")
plt.ylabel("Life Expectancy")
plt.title("Clustering of Countries")
plt.show()

# ==============================
# Regression (Fitting)
# ==============================
X = data[['gdp_per_capita']]
y = data['life_expectancy']

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

plt.figure()
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("GDP per Capita")
plt.ylabel("Life Expectancy")
plt.title("Regression Line")
plt.show()

# ==============================
# Conclusion
# ==============================
print("\nConclusion:")
print("There is a positive relationship between GDP per capita and life expectancy.")
print("Clustering groups countries based on development levels.")